### ISSUE TITLE
Vertical Spacing / Background Colors

### ISSUE THREAD

**Issue by tisto** [kitconcept/volto-light-theme#11]
# ToDo

- copy over the DLR vertical spacing
- put it in one single file
- possibly experiment with the row block and replace it at a later point with it

**Comment by steffenri** [comment]
This is done and can be looked at: https://light-theme.kitconcept.io/
The vertical spacing is not placed in one single file since it's part of the different blocks and they are spread out over multiple files. 
There's a variable that handles the spacing here: https://github.com/kitconcept/volto-light-theme/blob/a568566b9bbd76e01268fb4d275c29bbc536fd07/src/theme/_variables.scss#L92
