### ISSUE TITLE
Fat Menu

### ISSUE THREAD

**Issue by tisto** [kitconcept/volto-light-theme#208]
We need a fat menu layout and implementation. IMO the fat menu should be part of the Volto-Light-Theme. It can have a feature toggle to turn it off. Though, even that might not be necessary.

The Volto Light Theme design needs a fat menu to allow users to navigate to the second and third level of a site.

@davisagli @ericof @fredvd @danalvrz @steffenri what do you think?

**Comment by fredvd** [comment]
Yes this is a very common requirement. Serendipity, I just looked at a similar requirement for my 'pet Zest' Volto project with VLT that I had to focus on since end of last week to finally break through some blockers. More on that later and elsewhere.

I fiddled with using the ContextNavigation component in App.jsx to fake some kind of seond level navigation once you've selected a main section.  Personally and on a UX and mobile hover/touch/tap level I abhor the dynamic menu's, so if that suffies I'm fine for this project.  But also at another project from Zest there is this 'fat menu' in the wire frames.  

What I see there: the real challenge is that designers not often suggest 'only' clean navigation item only fat menu's. They show customised fat menu contents for every sub section to do some storytelling or give guidance there which is actually content you need to store somewhere :-O   They're basically dynanic mini pages in the menu.

My quick hack for a classic-UI project would be to store a content item in every subfolder with a fixed id and try to inject it on the right side of the built-in dropdownmenu.

**Comment by steffenri** [comment]
PR: https://github.com/kitconcept/volto-light-theme/pull/237

PR merged.

Works on dev: https://light-theme.kitconcept.io/

Closing.
